### ISSUE TITLE
Card 클래스 만들기

### ISSUE THREAD

**Issue by Hong-ji-min** [heem6woo/oop-OneCard#21]
## 👷To-do

- [ ] - number : int  = 카드 번호 생성
- [ ] + getNumber : int => 카드 번호 조회
- [ ] + setNumber : int
- [ ] + toString() : 어떤 카드인지 출력
- [ ] + compare(card1, card2) : 공개덱과 사용자가 낸 카드를 비교하는 기능
